# _*_ restclient _*_
#
# TODO add valid transit payloads for /generate requests

## Get home page

GET http://localhost:8021/
Accept-Charset: utf-8

## Perform NER on a text

POST http://localhost:8021/generate/ner
Accept-Charset: utf-8
Accept: application/transit+json

## Generate continuations of a text

POST http://localhost:8021/generate/sentences
Accept-Charset: utf-8
Accept: application/transit+json

## Generate a summary of a text

POST http://localhost:8021/generate/summary
Accept-Charset: utf-8
Accept: application/transit+json

## Generate a title for a text

POST http://localhost:8021/generate/title
Accept-Charset: utf-8
Accept: application/transit+json
